### PR TITLE
Creating a Utils  package

### PR DESCRIPTION
**Pull request by cacsphysics**
I am taking the BMPL github [User functions](https://github.com/dschaffner/BMPL/tree/master/User%20Functions) and creating a 'utils' package. 

- created a utils package
- added an index_funcs script. 
- Updated the bmpl/__init__.py file for the new package.

### CODE REVIEW

**Comment by dschaffner** [comment]
I will try to look through these over the weekend. I think we should definitely start trying to adopt a better naming schemes for all of these codes and use my clearly named labels.

**Comment by cacsphysics** [comment]
I will stop adding commits until @dschaffner looks through these.  

- commentation == documentation

**Comment by cacsphysics** [comment]
I am going to commit the utils branch.

**Comment by dschaffner** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cacsphysics** [comment]
I think you are required to push the changes. I think I have it set so that I need your review and approval.

**Comment by dschaffner** [comment]
Ok, merged.


-----------------------------------

David Schaffner

Associate Professor
Department of Physics
Bryn Mawr College
***@***.******@***.***>


________________________________

**Pull request merged**
